-- Phase 1 Data Preparation & Ingestion
-- Step 1: Snowflake environment setup

-- CREATE a warehouse
CREATE OR REPLACE WAREHOUSE WH_LAB
WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Use it:
USE WAREHOUSE WH_LAB;

-- Initialize the Snowflake DATABASE
CREATE OR REPLACE DATABASE ANYCOMPANY_LAB;

CREATE OR REPLACE SCHEMA ANYCOMPANY_LAB.BRONZE;
CREATE OR REPLACE SCHEMA ANYCOMPANY_LAB.SILVER;
CREATE OR REPLACE SCHEMA ANYCOMPANY_LAB.ANALYTICS;

-- Prepare data loading (Stage + formats)
-- 1-File formats
USE DATABASE ANYCOMPANY_LAB;
USE SCHEMA BRONZE;

-- CSV format WITH ',' delimiter

CREATE OR REPLACE FILE FORMAT FF_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  NULL_IF = ('', 'NULL');

-- CSV format WITH '\t' tab delimiter
CREATE OR REPLACE FILE FORMAT FF_TSV
  TYPE = CSV
  FIELD_DELIMITER = '\t'
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  NULL_IF = ('', 'NULL', 'null')
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- JSON format
  

CREATE OR REPLACE FILE FORMAT FF_JSON
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE;

-- 2- S3 stage
CREATE OR REPLACE STAGE STG_FOOD_BEVERAGE
  URL = 's3:--logbrain-datalake/datasets/food-beverage/'
  FILE_FORMAT = FF_CSV;

-- test 
LIST @STG_FOOD_BEVERAGE;
