-- Étape 3 – Chargement des données
--3.1 customer_demographics.csv

COPY INTO BRONZE.CUSTOMER_DEMOGRAPHICS
FROM @STG_FOOD_BEVERAGE/customer_demographics.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV)
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) FROM BRONZE.CUSTOMER_DEMOGRAPHICS;
SELECT * FROM BRONZE.CUSTOMER_DEMOGRAPHICS LIMIT 10;


--3.2 customer_service_interactions.csv
COPY INTO BRONZE.CUSTOMER_SERVICE_INTERACTIONS
FROM @STG_FOOD_BEVERAGE/customer_service_interactions.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV)
ON_ERROR = 'CONTINUE';

SELECT * FROM BRONZE.CUSTOMER_SERVICE_INTERACTIONS;

--3.3 financial_transactions.csv (⚠️ sensible)
COPY INTO BRONZE.FINANCIAL_TRANSACTIONS
FROM @STG_FOOD_BEVERAGE/financial_transactions.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV)
ON_ERROR = 'CONTINUE';


SELECT * FROM BRONZE.FINANCIAL_TRANSACTIONS LIMIT 10;


--3.4 promotions-data.csv

COPY INTO BRONZE.PROMOTIONS_DATA
FROM @STG_FOOD_BEVERAGE/promotions-data.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV)
ON_ERROR = 'CONTINUE';

SELECT * FROM BRONZE.PROMOTIONS_DATA LIMIT 10;

--3.5 marketing_campaigns.csv
COPY INTO BRONZE.MARKETING_CAMPAIGNS
FROM @STG_FOOD_BEVERAGE/marketing_campaigns.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV)
ON_ERROR = 'CONTINUE';

SELECT * FROM BRONZE.MARKETING_CAMPAIGNS LIMIT 10;

--3.6 product_reviews.csv

COPY INTO BRONZE.PRODUCT_REVIEWS
FROM @STG_FOOD_BEVERAGE/product_reviews.csv
FILE_FORMAT = (FORMAT_NAME = FF_TSV)
ON_ERROR = 'CONTINUE';

SELECT *
FROM BRONZE.PRODUCT_REVIEWS
LIMIT 10;

--3.7 logistics_and_shipping.csv
COPY INTO BRONZE.LOGISTICS_AND_SHIPPING
FROM @STG_FOOD_BEVERAGE/logistics_and_shipping.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV)
ON_ERROR = 'CONTINUE';

--3.8 supplier_information.csv
COPY INTO BRONZE.SUPPLIER_INFORMATION
FROM @STG_FOOD_BEVERAGE/supplier_information.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV)
ON_ERROR = 'CONTINUE';

--3.9 employee_records.csv
COPY INTO BRONZE.EMPLOYEE_RECORDS
FROM @STG_FOOD_BEVERAGE/employee_records.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV)
ON_ERROR = 'CONTINUE';


--3.10 inventory.json
COPY INTO BRONZE.INVENTORY_RAW
FROM @STG_FOOD_BEVERAGE/inventory.json
FILE_FORMAT = (FORMAT_NAME = FF_JSON)
ON_ERROR = 'CONTINUE';

SELECT raw FROM BRONZE.INVENTORY_RAW LIMIT 5;

--3.11 store_locations.json

COPY INTO BRONZE.STORE_LOCATIONS_RAW
FROM @STG_FOOD_BEVERAGE/store_locations.json
FILE_FORMAT = (FORMAT_NAME = FF_JSON)
ON_ERROR = 'CONTINUE';
